name       : cantarell-fonts
version    : '0.301'
release    : 9
source     :
    - https://download.gnome.org/sources/cantarell-fonts/0.301/cantarell-fonts-0.301.tar.xz : 3d35db0ac03f9e6b0d5a53577591b714238985f4cfc31a0aa17f26cd74675e83
license    : OFL-1.1
component  : desktop.gnome.core
summary    : GNOME Cantarell fonts
description: |
    GNOME Cantarell fonts - required for GNOME 3
builddeps  :
    - intltool
setup      : |
    %meson_configure -Dbuildappstream=false
build      : |
    %ninja_build
install    : |
    %ninja_install
