name        : cantarell-fonts
version     : 0.0.23
release     : 3
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/cantarell-fonts/0.0/cantarell-fonts-0.0.23.tar.xz : d85e165ac5d676d6b21c7870d8243cb612a2dc766d91fda788d56d5f5ad5db4e
license     : GPL-2.0+
summary     : GNOME Cantarell fonts
description : |
    GNOME Cantarell fonts - required for GNOME 3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
