name       : cantarell-fonts
version    : '0.201'
release    : 8
source     :
    - https://download.gnome.org/sources/cantarell-fonts/0.201/cantarell-fonts-0.201.tar.xz : b61f64e5f6a48aa0abc7a53cdcbce60de81908ca36048a64730978fcd9ac9863
license    : OFL-1.1
component  : desktop.gnome.core
summary    : GNOME Cantarell fonts
description: |
    GNOME Cantarell fonts - required for GNOME 3
builddeps  :
    - intltool
setup      : |
    %meson_configure -Dbuildappstream=false
build      : |
    %ninja_build
install    : |
    %ninja_install
