name       : cantarell-fonts
version    : '0.110'
release    : 7
source     :
    - https://download.gnome.org/sources/cantarell-fonts/0.110/cantarell-fonts-0.110.tar.xz : a454d75db51ab5b76b4c5fa2d779e8796ee01102847d50311dc8ca4e20a034a7
license    : OFL-1.1
component  : desktop.gnome.core
summary    : GNOME Cantarell fonts
description: |
    GNOME Cantarell fonts - required for GNOME 3
builddeps  :
    - intltool
setup      : |
    %meson_configure -Dbuildappstream=false
build      : |
    %ninja_build
install    : |
    %ninja_install
