name       : cantarell-fonts
version    : 0.0.24
release    : 4
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/cantarell-fonts/0.0/cantarell-fonts-0.0.24.tar.xz : 9cad649ae84f7e4ca1be637c27e2fa19e1fbf00d4bf6480171ccfad405b39264
license    : GPL-2.0+
summary    : GNOME Cantarell fonts
description: |
    GNOME Cantarell fonts - required for GNOME 3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
