name       : cantarell-fonts
version    : 0.0.25
release    : 5
source     :
    - https://ftp.gnome.org/pub/GNOME/sources/cantarell-fonts/0.0/cantarell-fonts-0.0.25.tar.xz : 14a228aa0b516dfc367b434a850f955a00c57fc549cbb05348e2b150196a737f
license    : OFL-1.1
component  : desktop.gnome.core
summary    : GNOME Cantarell fonts
description: |
    GNOME Cantarell fonts - required for GNOME 3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
